In [1]:
import pandas as pd

In [2]:
import ast

In [3]:
movies = pd.read_csv("tmdb_5000_movies.csv")
credits = pd.read_csv("tmdb_5000_credits.csv")

In [4]:
print("Movies:", movies.shape)
print("Credits:", credits.shape)

Movies: (4803, 20)
Credits: (4803, 4)

In [5]:
print(movies.columns)
print(credits.columns)

Index(['budget', 'genres', 'homepage', 'id', 'keywords', 'original_language',
       'original_title', 'overview', 'popularity', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title', 'vote_average',
       'vote_count'],
      dtype='str')
Index(['movie_id', 'title', 'cast', 'crew'], dtype='str')

In [6]:
movies.isnull().sum()

budget                     0
genres                     0
homepage                3091
id                         0
keywords                   0
original_language          0
original_title             0
overview                   3
popularity                 0
production_companies       0
production_countries       0
release_date               1
revenue                    0
runtime                    2
spoken_languages           0
status                     0
tagline                  844
title                      0
vote_average               0
vote_count                 0
dtype: int64

In [7]:
credits.isnull().sum()

movie_id    0
title       0
cast        0
crew        0
dtype: int64

In [8]:
credits.duplicated().sum()

np.int64(0)

In [9]:
movies.duplicated().sum()

np.int64(0)

In [10]:
movies[['title', 'genres', 'keywords', 'overview',
        'runtime', 'original_language',
        'vote_average', 'vote_count']].head()

,title,genres,keywords,overview,runtime,original_language,vote_average,vote_count
0,Avatar,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","In the 22nd century, a paraplegic Marine is di...",162.0,en,7.2,11800
1,Pirates of the Caribbean: At World's End,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","Captain Barbossa, long believed to be dead, ha...",169.0,en,6.9,4500
2,Spectre,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",A cryptic message from Bond’s past sends him o...,148.0,en,6.3,4466
3,The Dark Knight Rises,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",Following the death of District Attorney Harve...,165.0,en,7.6,9106
4,John Carter,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","John Carter is a war-weary, former military ca...",132.0,en,6.1,2124

In [11]:
movies = movies[
    ['id',
     'title',
     'genres',
     'keywords',
     'overview',
     'runtime',
     'original_language',
     'vote_average',
     'vote_count']
]

In [12]:
credits = credits[
    ['movie_id',
     'title',
     'cast',
     'crew']
]

In [13]:
movies.columns

Index(['id', 'title', 'genres', 'keywords', 'overview', 'runtime',
       'original_language', 'vote_average', 'vote_count'],
      dtype='str')

In [14]:
credits.columns

Index(['movie_id', 'title', 'cast', 'crew'], dtype='str')

In [15]:
movies.isnull().sum()

id                   0
title                0
genres               0
keywords             0
overview             3
runtime              2
original_language    0
vote_average         0
vote_count           0
dtype: int64

In [16]:
movies['overview'] = movies['overview'].fillna('')

In [17]:
movies['runtime'] = movies['runtime'].fillna(movies['runtime'].median())

In [18]:
movies.isnull().sum()

id                   0
title                0
genres               0
keywords             0
overview             0
runtime              0
original_language    0
vote_average         0
vote_count           0
dtype: int64

In [19]:
credits.isnull().sum()

movie_id    0
title       0
cast        0
crew        0
dtype: int64

In [20]:
movies = movies.merge(
    credits,
    left_on='id',
    right_on='movie_id'
)

In [21]:
movies.shape

(4803, 13)

In [22]:
movies.columns

Index(['id', 'title_x', 'genres', 'keywords', 'overview', 'runtime',
       'original_language', 'vote_average', 'vote_count', 'movie_id',
       'title_y', 'cast', 'crew'],
      dtype='str')

In [23]:
movies.drop(['title_y', 'movie_id'], axis=1, inplace=True)

In [24]:
movies.rename(columns={'title_x': 'title'}, inplace=True)

In [25]:
movies.columns

Index(['id', 'title', 'genres', 'keywords', 'overview', 'runtime',
       'original_language', 'vote_average', 'vote_count', 'cast', 'crew'],
      dtype='str')

In [26]:
movies.to_csv("smartmovie_dataset.csv", index=False)

In [27]:
movies[['title', 'genres', 'keywords', 'cast', 'crew']].head()

,title,genres,keywords,cast,crew
0,Avatar,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,Pirates of the Caribbean: At World's End,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,Spectre,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,The Dark Knight Rises,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,John Carter,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [28]:
def convert_names(text):
    result = []
    
    for item in ast.literal_eval(text):
        result.append(item['name'])
        
    return result

In [29]:
movies['genres'] = movies['genres'].apply(convert_names)
movies['keywords'] = movies['keywords'].apply(convert_names)

In [30]:
movies[['title', 'genres', 'keywords']].head()

,title,genres,keywords
0,Avatar,"[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon..."
1,Pirates of the Caribbean: At World's End,"[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ..."
2,Spectre,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi..."
3,The Dark Knight Rises,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i..."
4,John Carter,"[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel..."

In [31]:
def convert_cast(text):
    result = []
    
    for item in ast.literal_eval(text)[:3]:
        result.append(item['name'])
        
    return result

In [32]:
movies['cast'] = movies['cast'].apply(convert_cast)

In [33]:
movies[['title', 'cast']].head()

,title,cast
0,Avatar,"[Sam Worthington, Zoe Saldana, Sigourney Weaver]"
1,Pirates of the Caribbean: At World's End,"[Johnny Depp, Orlando Bloom, Keira Knightley]"
2,Spectre,"[Daniel Craig, Christoph Waltz, Léa Seydoux]"
3,The Dark Knight Rises,"[Christian Bale, Michael Caine, Gary Oldman]"
4,John Carter,"[Taylor Kitsch, Lynn Collins, Samantha Morton]"

In [34]:
def get_director(text):
    for item in ast.literal_eval(text):
        if item['job'] == 'Director':
            return item['name']
    
    return ''

In [35]:
movies['director'] = movies['crew'].apply(get_director)

In [36]:
movies[['title', 'director']].head()

                                      title           director
0                                    Avatar      James Cameron
1  Pirates of the Caribbean: At World's End     Gore Verbinski
2                                   Spectre         Sam Mendes
3                     The Dark Knight Rises  Christopher Nolan
4                               John Carter     Andrew Stanton

In [37]:
movies.drop('crew', axis=1, inplace=True)

In [38]:
movies['overview'] = movies['overview'].apply(lambda x: x.split())

In [39]:
movies['genres'] = movies['genres'].apply(
    lambda x: [i.replace(" ", "") for i in x]
)
movies['keywords'] = movies['keywords'].apply(
    lambda x: [i.replace(" ", "") for i in x]
)
movies['cast'] = movies['cast'].apply(
    lambda x: [i.replace(" ", "") for i in x]
)
movies['director'] = movies['director'].apply(
    lambda x: x.replace(" ", "")
)

In [40]:
movies['tags'] = (
    movies['overview']
    + movies['genres']
    + movies['keywords']
    + movies['cast']
    + movies['director'].apply(lambda x: [x])
)

In [41]:
movies[['title', 'tags']].head()

,title,tags
0,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d..."
2,Spectre,"[A, cryptic, message, from, Bond’s, past, send..."
3,The Dark Knight Rises,"[Following, the, death, of, District, Attorney..."
4,John Carter,"[John, Carter, is, a, war-weary,, former, mili..."

In [42]:
movies['tags'] = movies['tags'].apply(lambda x: " ".join(x))

In [43]:
print(type(movies['tags'][0]))

<class 'str'>

In [44]:
movies['tags'] = (
    movies['overview']
    + movies['genres']
    + movies['keywords']
    + movies['cast']
    + movies['director'].apply(lambda x: [x])
)

In [45]:
movies['tags'] = movies['tags'].apply(lambda x: " ".join(x))

In [46]:
movies['tags'] = movies['tags'].apply(lambda x: x.lower())

In [47]:
movies[['title', 'tags']].head(2)

,title,tags
0,Avatar,"in the 22nd century, a paraplegic marine is di..."
1,Pirates of the Caribbean: At World's End,"captain barbossa, long believed to be dead, ha..."

In [48]:
movies['director'] = movies['director'].fillna('')

In [49]:
movies.isnull().sum()

id                   0
title                0
genres               0
keywords             0
overview             0
runtime              0
original_language    0
vote_average         0
vote_count           0
cast                 0
director             0
tags                 0
dtype: int64

In [50]:
movies.to_csv("smartmovie_preprocessed.csv", index=False)

In [51]:
movies['director'] = movies['director'].fillna('unknown')

In [52]:
movies['director'].isnull().sum()

np.int64(0)

In [53]:
movies['tags'] = (
    movies['overview']
    + movies['genres']
    + movies['keywords']
    + movies['cast']
    + movies['director'].apply(lambda x: [x])
)

In [54]:
movies['tags'] = movies['tags'].apply(lambda x: " ".join(x))

In [55]:
movies['tags'] = movies['tags'].str.lower()

In [56]:
print(movies['director'].isnull().sum())
print(movies['tags'].isnull().sum())

0
0

In [57]:
movies[['title', 'director', 'tags']].head()

,title,director,tags
0,Avatar,JamesCameron,"in the 22nd century, a paraplegic marine is di..."
1,Pirates of the Caribbean: At World's End,GoreVerbinski,"captain barbossa, long believed to be dead, ha..."
2,Spectre,SamMendes,a cryptic message from bond’s past sends him o...
3,The Dark Knight Rises,ChristopherNolan,following the death of district attorney harve...
4,John Carter,AndrewStanton,"john carter is a war-weary, former military ca..."

In [58]:
movies.to_csv("smartmovie_preprocessed.csv", index=False)

In [59]:
print(movies['director'].isnull().sum())

movies['director'] = movies['director'].fillna('unknown')

print(movies['director'].isnull().sum())

0
0

In [60]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [61]:
tfidf = TfidfVectorizer(
    max_features=5000,
    stop_words='english'
)

In [62]:
vectors = tfidf.fit_transform(movies['tags'])

In [63]:
print(vectors.shape)

(4803, 5000)

In [64]:
from sklearn.metrics.pairwise import cosine_similarity

In [65]:
similarity = cosine_similarity(vectors)

In [66]:
print(similarity.shape)

(4803, 4803)

In [67]:
def recommend(movie):
    index = movies[movies['title'] == movie].index[0]
    distances = list(enumerate(similarity[index]))
    distances = sorted(distances, key=lambda x: x[1], reverse=True)
    print(f"\nMovies similar to {movie}:\n")
    for i in distances[1:6]:
        print(movies.iloc[i[0]].title)

In [68]:
recommend("Interstellar")

Movies similar to Interstellar:

Apollo 13
Space Pirate Captain Harlock
Space Cowboys
The Martian
Moonraker

In [69]:
recommend("Avatar")

Movies similar to Avatar:

Falcon Rising
Battle: Los Angeles
Apollo 18
Star Trek Into Darkness
Titan A.E.

In [70]:
recommend("The Dark Knight")

Movies similar to The Dark Knight:

The Dark Knight Rises
Batman Returns
Batman Begins
Batman Forever
Batman: The Dark Knight Returns, Part 2

In [71]:
def recommend(movie):
    index = movies[movies['title'] == movie].index[0]
    distances = list(enumerate(similarity[index]))
    distances = sorted(distances, key=lambda x: x[1], reverse=True)
    print(f"\nRecommended movies for '{movie}':\n")
    for i in distances[1:6]:
        row = movies.iloc[i[0]]
        print(f"🎬 {row['title']}")
        print(f"⭐ Rating: {row['vote_average']}")
        print(f"⏱ Runtime: {int(row['runtime'])} minutes")
        print(f"🌐 Language: {row['original_language']}")
        print("-"*40)

In [72]:
recommend("Inception")

Recommended movies for 'Inception':

🎬 Don Jon
⭐ Rating: 5.9
⏱ Runtime: 90 minutes
🌐 Language: en
----------------------------------------
🎬 Premium Rush
⭐ Rating: 6.2
⏱ Runtime: 91 minutes
🌐 Language: en
----------------------------------------
🎬 Cypher
⭐ Rating: 6.7
⏱ Runtime: 95 minutes
🌐 Language: en
----------------------------------------
🎬 Hesher
⭐ Rating: 6.7
⏱ Runtime: 106 minutes
🌐 Language: en
----------------------------------------
🎬 Duplex
⭐ Rating: 5.9
⏱ Runtime: 89 minutes
🌐 Language: en
----------------------------------------

In [73]:
def personalized_recommend(movie, language="Any", min_rating=7.0, max_runtime=180):
    index = movies[movies['title'] == movie].index[0]
    distances = list(enumerate(similarity[index]))
    distances = sorted(distances, key=lambda x: x[1], reverse=True)
    count = 0
    print(f"\nPersonalized recommendations for '{movie}':\n")
    for i in distances[1:]:
        row = movies.iloc[i[0]]
        if language != "Any" and row['original_language'] != language:
            continue
        if row['vote_average'] < min_rating:
            continue
        if row['runtime'] > max_runtime:
            continue
        print(f"🎬 {row['title']}")
        print(f"⭐ Rating: {row['vote_average']}")
        print(f"⏱ Runtime: {int(row['runtime'])} min")
        print(f"🌐 Language: {row['original_language']}")
        print("Why recommended?")
        print("✓ Similar to your selected movie")
        print("✓ Matches your preferences")
        print("-"*35)
        count += 1
        if count == 5:
            break

In [74]:
personalized_recommend(
    "Interstellar",
    language="en",
    min_rating=8,
    max_runtime=150
)

Personalized recommendations for 'Interstellar':

🎬 There Goes My Baby
⭐ Rating: 8.5
⏱ Runtime: 99 min
🌐 Language: en
Why recommended?
✓ Similar to your selected movie
✓ Matches your preferences
-----------------------------------
🎬 Inception
⭐ Rating: 8.1
⏱ Runtime: 148 min
🌐 Language: en
Why recommended?
✓ Similar to your selected movie
✓ Matches your preferences
-----------------------------------
🎬 Star Wars
⭐ Rating: 8.1
⏱ Runtime: 121 min
🌐 Language: en
Why recommended?
✓ Similar to your selected movie
✓ Matches your preferences
-----------------------------------
🎬 Forrest Gump
⭐ Rating: 8.2
⏱ Runtime: 142 min
🌐 Language: en
Why recommended?
✓ Similar to your selected movie
✓ Matches your preferences
-----------------------------------
🎬 The Prestige
⭐ Rating: 8.0
⏱ Runtime: 130 min
🌐 Language: en
Why recommended?
✓ Similar to your selected movie
✓ Matches your preferences
-----------------------------------

In [75]:
personalized_recommend(
    "Avatar",
    language="en",
    min_rating=7.5,
    max_runtime=170
)

Personalized recommendations for 'Avatar':

🎬 Aliens
⭐ Rating: 7.7
⏱ Runtime: 137 min
🌐 Language: en
Why recommended?
✓ Similar to your selected movie
✓ Matches your preferences
-----------------------------------
🎬 Edge of Tomorrow
⭐ Rating: 7.6
⏱ Runtime: 113 min
🌐 Language: en
Why recommended?
✓ Similar to your selected movie
✓ Matches your preferences
-----------------------------------
🎬 Alien
⭐ Rating: 7.9
⏱ Runtime: 117 min
🌐 Language: en
Why recommended?
✓ Similar to your selected movie
✓ Matches your preferences
-----------------------------------
🎬 Moon
⭐ Rating: 7.6
⏱ Runtime: 97 min
🌐 Language: en
Why recommended?
✓ Similar to your selected movie
✓ Matches your preferences
-----------------------------------
🎬 The Thing
⭐ Rating: 7.8
⏱ Runtime: 109 min
🌐 Language: en
Why recommended?
✓ Similar to your selected movie
✓ Matches your preferences
-----------------------------------

In [76]:
!pip install streamlit

Requirement already satisfied: streamlit in C:\Users\sahit\AppData\Local\Programs\Python\Python312\Lib\site-packages (1.64.0)
Requirement already satisfied: altair!=5.4.0,!=5.4.1,<7,>=5.0.0 in C:\Users\sahit\AppData\Local\Programs\Python\Python312\Lib\site-packages (from streamlit) (6.3.0)
Requirement already satisfied: click<9,>=7.0 in C:\Users\sahit\AppData\Local\Programs\Python\Python312\Lib\site-packages (from streamlit) (8.5.0)
Requirement already satisfied: numpy<3,>=1.23 in C:\Users\sahit\AppData\Local\Programs\Python\Python312\Lib\site-packages (from streamlit) (2.5.1)
Requirement already satisfied: packaging>=20 in C:\Users\sahit\AppData\Roaming\Python\Python312\site-packages (from streamlit) (26.2)
Requirement already satisfied: pandas<4,>=1.4.0 in C:\Users\sahit\AppData\Local\Programs\Python\Python312\Lib\site-packages (from streamlit) (3.0.3)
Requirement already satisfied: pillow<13,>=7.1.0 in C:\Users\sahit\AppData\Local\Programs\Python\Python312\Lib\site-packages (from streamlit) (12.3.0)
Requirement already satisfied: pydeck<1,>=0.8.0b4 in C:\Users\sahit\AppData\Local\Programs\Python\Python312\Lib\site-packages (from streamlit) (0.9.3)
Requirement already satisfied: protobuf<8,>=5.26.1 in C:\Users\sahit\AppData\Local\Programs\Python\Python312\Lib\site-packages (from streamlit) (7.36.2)
Requirement already satisfied: pyarrow!=25.0.0,<26,>=7.0 in C:\Users\sahit\AppData\Local\Programs\Python\Python312\Lib\site-packages (from streamlit) (25.0.1)
Requirement already satisfied: requests<3,>=2.27 in C:\Users\sahit\AppData\Local\Programs\Python\Python312\Lib\site-packages (from streamlit) (2.34.2)
Requirement already satisfied: toml<2,>=0.10.1 in C:\Users\sahit\AppData\Local\Programs\Python\Python312\Lib\site-packages (from streamlit) (0.10.2)
Requirement already satisfied: typing-extensions<5,>=4.10.0 in C:\Users\sahit\AppData\Local\Programs\Python\Python312\Lib\site-packages (from streamlit) (4.16.0)
Requirement already satisfied: starlette<2,>=0.46.0 in C:\Users\sahit\AppData\Local\Programs\Python\Python312\Lib\site-packages (from streamlit) (1.7.0)
Requirement already satisfied: uvicorn<1,>=0.30.0 in C:\Users\sahit\AppData\Local\Programs\Python\Python312\Lib\site-packages (from streamlit) (0.54.0)
Requirement already satisfied: httptools<1,>=0.6.3 in C:\Users\sahit\AppData\Local\Programs\Python\Python312\Lib\site-packages (from streamlit) (0.8.0)
Requirement already satisfied: anyio<5,>=4.0.0 in C:\Users\sahit\AppData\Local\Programs\Python\Python312\Lib\site-packages (from streamlit) (4.14.2)
Requirement already satisfied: python-multipart<1,>=0.0.10 in C:\Users\sahit\AppData\Local\Programs\Python\Python312\Lib\site-packages (from streamlit) (0.0.32)
Requirement already satisfied: websockets<17,>=12.0.0 in C:\Users\sahit\AppData\Local\Programs\Python\Python312\Lib\site-packages (from streamlit) (16.1.1)
Requirement already satisfied: itsdangerous<3,>=2.1.2 in C:\Users\sahit\AppData\Local\Programs\Python\Python312\Lib\site-packages (from streamlit) (2.2.0)
Requirement already satisfied: watchdog<7,>=2.1.5 in C:\Users\sahit\AppData\Local\Programs\Python\Python312\Lib\site-packages (from streamlit) (6.0.0)
Requirement already satisfied: jinja2 in C:\Users\sahit\AppData\Local\Programs\Python\Python312\Lib\site-packages (from altair!=5.4.0,!=5.4.1,<7,>=5.0.0->streamlit) (3.1.6)
Requirement already satisfied: jsonschema>=3.0 in C:\Users\sahit\AppData\Local\Programs\Python\Python312\Lib\site-packages (from altair!=5.4.0,!=5.4.1,<7,>=5.0.0->streamlit) (4.26.0)
Requirement already satisfied: narwhals>=2.4.0 in C:\Users\sahit\AppData\Local\Programs\Python\Python312\Lib\site-packages (from altair!=5.4.0,!=5.4.1,<7,>=5.0.0->streamlit) (2.23.0)
Requirement already satisfied: idna>=2.8 in C:\Users\sahit\AppData\Local\Programs\Python\Python312\Lib\site-packages (from anyio<5,>=4.0.0->streamlit) (3.18)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\sahit\AppData\Roaming\Python\Python312\site-packages (from pandas<4,>=1.4.0->streamlit) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\sahit\AppData\Local\Programs\Python\Python312\Lib\site-packages (from pandas<4,>=1.4.0->streamlit) (2026.2)
Requirement already satisfied: charset_normalizer<4,>=2 in C:\Users\sahit\AppData\Local\Programs\Python\Python312\Lib\site-packages (from requests<3,>=2.27->streamlit) (3.4.9)
Requirement already satisfied: urllib3<3,>=1.26 in C:\Users\sahit\AppData\Local\Programs\Python\Python312\Lib\site-packages (from requests<3,>=2.27->streamlit) (2.7.0)
Requirement already satisfied: certifi>=2023.5.7 in C:\Users\sahit\AppData\Local\Programs\Python\Python312\Lib\site-packages (from requests<3,>=2.27->streamlit) (2026.7.22)
Requirement already satisfied: h11>=0.8 in C:\Users\sahit\AppData\Local\Programs\Python\Python312\Lib\site-packages (from uvicorn<1,>=0.30.0->streamlit) (0.16.0)
Requirement already satisfied: MarkupSafe>=2.0 in C:\Users\sahit\AppData\Local\Programs\Python\Python312\Lib\site-packages (from jinja2->altair!=5.4.0,!=5.4.1,<7,>=5.0.0->streamlit) (3.0.3)
Requirement already satisfied: attrs>=22.2.0 in C:\Users\sahit\AppData\Local\Programs\Python\Python312\Lib\site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=5.0.0->streamlit) (26.1.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in C:\Users\sahit\AppData\Local\Programs\Python\Python312\Lib\site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=5.0.0->streamlit) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in C:\Users\sahit\AppData\Local\Programs\Python\Python312\Lib\site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=5.0.0->streamlit) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in C:\Users\sahit\AppData\Local\Programs\Python\Python312\Lib\site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=5.0.0->streamlit) (2026.6.3)
Requirement already satisfied: six>=1.5 in C:\Users\sahit\AppData\Roaming\Python\Python312\site-packages (from python-dateutil>=2.8.2->pandas<4,>=1.4.0->streamlit) (1.17.0)

In [77]:
import pickle
pickle.dump(movies, open("movies.pkl", "wb"))
pickle.dump(similarity, open("similarity.pkl", "wb"))

In [78]:
print(movies.shape)
print(movies.columns.tolist())

print("TF-IDF:", type(tfidf))

if 'vectors' in globals():
    print("Vectors:", vectors.shape)
else:
    print("Vectors not found")

if 'similarity' in globals():
    print("Similarity:", similarity.shape)
else:
    print("Similarity not found")

(4803, 12)
['id', 'title', 'genres', 'keywords', 'overview', 'runtime', 'original_language', 'vote_average', 'vote_count', 'cast', 'director', 'tags']
TF-IDF: <class 'sklearn.feature_extraction.text.TfidfVectorizer'>
Vectors: (4803, 5000)
Similarity: (4803, 4803)

In [79]:
import pickle
pickle.dump(movies, open("movies.pkl", "wb"))
pickle.dump(tfidf, open("tfidf.pkl", "wb"))
pickle.dump(vectors, open("vectors.pkl", "wb"))
print("Files saved successfully!")

Files saved successfully!

In [80]:
import requests
API_KEY = "5bbeb995a3b19da61b79eff384955e6e"
url = "https://api.themoviedb.org/3/search/movie"
params = {
    "api_key": API_KEY,
    "query": "Interstellar"
}
response = requests.get(url, params=params)
print(response.status_code)
print(response.json()["results"][0]["title"])

200
Interstellar

In [87]:
import requests

API_KEY = "5bbeb995a3b19da61b79eff384955e6e"

url = "https://api.themoviedb.org/3/search/movie"

params = {
    "api_key": API_KEY,
    "query": "Interstellar"
}

headers = {
    "User-Agent": "Mozilla/5.0"
}

session = requests.Session()
session.trust_env = False

try:
    response = session.get(
        url,
        params=params,
        headers=headers,
        timeout=20
    )

    print("Status:", response.status_code)

    data = response.json()

    if data.get("results"):
        print("Movie found:", data["results"][0]["title"])
    else:
        print("No movie found")

except Exception as e:
    print("Error:", e)

Status: 200
Movie found: Interstellar

In [91]:
import requests
url = "https://api.themoviedb.org/3/search/movie"
ACCESS_TOKEN = "eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiI1YmJlYjk5NWEzYjE5ZGE2MWI3OWVmZjM4NDk1NWU2ZSIsIm5iZiI6MTc5MTEyMDIzNC43MzQwMDAyLCJzdWIiOiI2YWMyNTM2YTcyNGYzM2FkZDQ0NmIxZTciLCJzY29wZXMiOlsiYXBpX3JlYWQiXSwidmVyc2lvbiI6MX0.F1XW5tUnQMiSruH-3VZ5he9DIpwSdJ41QPA9ZEsrfhg"
headers = {
    "Authorization": f"Bearer {ACCESS_TOKEN}",
    "accept": "application/json"
}
params = {
    "query": "Interstellar"
}
response = requests.get(url, headers=headers, params=params)
data = response.json()
movie_id = data["results"][0]["id"]
print("Movie ID:", movie_id)
print("Movie:", data["results"][0]["title"])

Movie ID: 157336
Movie: Interstellar

In [95]:
import requests

movie_id = data["results"][0]["id"]

url = f"https://api.themoviedb.org/3/movie/{movie_id}"

params = {
    "append_to_response": "credits,keywords"
}

response = requests.get(url, headers=headers, params=params)

movie_details = response.json()

print("Title:", movie_details["title"])
print("Overview:", movie_details["overview"])
print("Genres:", [g["name"] for g in movie_details["genres"]])
print("Language:", movie_details["original_language"])

Title: Interstellar
Overview: The adventures of a group of explorers who make use of a newly discovered wormhole to surpass the limitations on human space travel and conquer the vast distances involved in an interstellar voyage.
Genres: ['Adventure', 'Drama', 'Science Fiction']
Language: en

In [96]:
def create_tmdb_tags(movie):
    parts = []
    parts.append(movie.get("overview", ""))
    for genre in movie.get("genres", []):
        parts.append(genre.get("name", ""))
    keywords = movie.get("keywords", {}).get("keywords", [])
    for keyword in keywords:
        parts.append(keyword.get("name", ""))
    cast = movie.get("credits", {}).get("cast", [])
    for person in cast[:5]:
        parts.append(person.get("name", ""))
    crew = movie.get("credits", {}).get("crew", [])
    for person in crew:
        if person.get("job") == "Director":
            parts.append(person.get("name", ""))
    return " ".join(parts).lower()
tmdb_tags = create_tmdb_tags(movie_details)
print("Movie:", movie_details["title"])
print("Tags:")
print(tmdb_tags)

Movie: Interstellar
Tags:
the adventures of a group of explorers who make use of a newly discovered wormhole to surpass the limitations on human space travel and conquer the vast distances involved in an interstellar voyage. adventure drama science fiction spacecraft race against time artificial intelligence (a.i.) nasa time warp dystopia expedition time travel space travel wormhole famine hibernation black hole quantum mechanics family relationships space planet astronaut scientist single father space station gravity space adventure time-manipulation cryonics father daughter relationship 2060s audacious enthusiastic matthew mcconaughey anne hathaway michael caine jessica chastain casey affleck christopher nolan

In [97]:
from sklearn.metrics.pairwise import cosine_similarity
tmdb_vector = tfidf.transform([tmdb_tags])
scores = cosine_similarity(tmdb_vector, vectors)[0]
top_indexes = scores.argsort()[::-1][:10]
print("Movies similar to:", movie_details["title"])
print()
for i in top_indexes:
    print(movies.iloc[i]["title"], "->", round(scores[i], 3))

Movies similar to: Interstellar

Interstellar -> 0.479
Space Pirate Captain Harlock -> 0.329
Lost in Space -> 0.276
Silent Running -> 0.235
Capricorn One -> 0.232
Gattaca -> 0.231
Gravity -> 0.225
Space Chimps -> 0.219
Moonraker -> 0.216
Deep Impact -> 0.214

In [98]:
top_indexes = scores.argsort()[::-1]
recommendations = []
for i in top_indexes:
    title = movies.iloc[i]["title"]
    if title.lower() == movie_details["title"].lower():
        continue
    recommendations.append((title, scores[i]))
    if len(recommendations) == 5:
        break
print("Top 5 recommendations:")
print()
for title, score in recommendations:
    print(title, "->", round(score, 3))

Top 5 recommendations:

Space Pirate Captain Harlock -> 0.329
Lost in Space -> 0.276
Silent Running -> 0.235
Capricorn One -> 0.232
Gattaca -> 0.231

In [99]:
url = f"https://api.themoviedb.org/3/movie/{movie_id}/similar"
params = {
    "language": "en-US",
    "page": 1
}
response = requests.get(url, headers=headers, params=params)
similar_data = response.json()
print("TMDB similar movies:")
print()
for movie in similar_data["results"][:10]:
    print(movie["title"])

TMDB similar movies:

The Terminator
Doctor Who: Planet of Fire
Star Trek: Generations
Back to the Future Part III
Star Trek II: The Wrath of Khan
Minority Report
Star Trek: First Contact
Star Trek: Insurrection
Star Trek: Nemesis
Terminator 3: Rise of the Machines

In [105]:
tmdb_candidates = []

for movie in similar_data["results"][:10]:

    tags = (
        movie.get("title", "") + " " +
        movie.get("overview", "") + " " +
        " ".join(str(x) for x in movie.get("genre_ids", []))
    ).lower()

    tmdb_candidates.append({
        "id": movie["id"],
        "title": movie["title"],
        "tags": tags,
        "rating": movie.get("vote_average", 0),
        "language": movie.get("original_language", "")
    })

print("TMDB candidates:", len(tmdb_candidates))

for movie in tmdb_candidates:
    print(movie["title"])

TMDB candidates: 10
The Terminator
Doctor Who: Planet of Fire
Star Trek: Generations
Back to the Future Part III
Star Trek II: The Wrath of Khan
Minority Report
Star Trek: First Contact
Star Trek: Insurrection
Star Trek: Nemesis
Terminator 3: Rise of the Machines

In [106]:
tmdb_scores = []

for movie in tmdb_candidates:

    movie_vector = tfidf.transform([movie["tags"]])

    score = cosine_similarity(tmdb_vector, movie_vector)[0][0]

    tmdb_scores.append({
        "title": movie["title"],
        "score": score,
        "rating": movie["rating"],
        "language": movie["language"],
        "id": movie["id"]
    })

tmdb_scores = sorted(
    tmdb_scores,
    key=lambda x: x["score"],
    reverse=True
)

print("TMDB movies ranked by your TF-IDF model:")
print()

for movie in tmdb_scores:
    print(movie["title"], "->", round(movie["score"], 3))

TMDB movies ranked by your TF-IDF model:

Star Trek: First Contact -> 0.08
Star Trek: Nemesis -> 0.07
Star Trek: Insurrection -> 0.062
Back to the Future Part III -> 0.032
Star Trek: Generations -> 0.022
Doctor Who: Planet of Fire -> 0.017
The Terminator -> 0.016
Star Trek II: The Wrath of Khan -> 0.0
Minority Report -> 0.0
Terminator 3: Rise of the Machines -> 0.0

In [109]:
# Local recommendations
local_results = []
for title, score in recommendations:
    row = movies[movies["title"] == title].iloc[0]

    local_results.append({
        "title": title,
        "score": score,
        "source": "Your Dataset",
        "rating": row["vote_average"],
        "language": row["original_language"]
    })
external_results = []
for movie in tmdb_scores:
    external_results.append({
        "title": movie["title"],
        "score": movie["score"],
        "source": "TMDB",
        "rating": movie["rating"],
        "language": movie["language"]
    })
# Combine both
combined_results = local_results + external_results
combined_results = sorted(
    combined_results,
    key=lambda x: x["score"],
    reverse=True
)
top_5 = combined_results[:5]
print("Top 5 Recommendations:\n")
for i, movie in enumerate(top_5, 1):
    print(
        i,
        movie["title"],
        "->",
        round(movie["score"], 3),
        "->",
        movie["source"]
    )

Top 5 Recommendations:

1 Space Pirate Captain Harlock -> 0.329 -> Your Dataset
2 Lost in Space -> 0.276 -> Your Dataset
3 Silent Running -> 0.235 -> Your Dataset
4 Capricorn One -> 0.232 -> Your Dataset
5 Gattaca -> 0.231 -> Your Dataset

In [110]:
# Give rank scores to local movies
for i, movie in enumerate(local_results):
    movie["rank_score"] = 1 - (i / len(local_results))
for i, movie in enumerate(external_results):
    movie["rank_score"] = 1 - (i / len(external_results))
combined_results = local_results + external_results
combined_results = sorted(
    combined_results,
    key=lambda x: x["rank_score"],
    reverse=True
)
top_5 = combined_results[:5]
print("Top 5 Recommendations:\n")
for i, movie in enumerate(top_5, 1):
    print(
        i,
        movie["title"],
        "->",
        round(movie["rank_score"], 3),
        "->",
        movie["source"]
    )

Top 5 Recommendations:

1 Space Pirate Captain Harlock -> 1.0 -> Your Dataset
2 Star Trek: First Contact -> 1.0 -> TMDB
3 Star Trek: Nemesis -> 0.9 -> TMDB
4 Lost in Space -> 0.8 -> Your Dataset
5 Star Trek: Insurrection -> 0.8 -> TMDB